### ISSUE TITLE
Proof of work

### ISSUE THREAD

**Issue by fjaokdp** [V3RDAD/i3p#2]
![2](https://user-images.githubusercontent.com/90276506/233735047-a3525d92-c624-41b3-b685-5ca92a0eed3a.png)
![4](https://user-images.githubusercontent.com/90276506/233736497-4dac9411-5091-4c2e-8fd2-bf63e2d8b7bc.png)
![3](https://user-images.githubusercontent.com/90276506/233736737-8d4356be-f135-4c66-a574-574ab5751fef.png)

**Comment by V3RDAD** [comment]
![port_10001](https://user-images.githubusercontent.com/50222317/233779404-9d00fa6b-33d8-4034-9bc2-7d9f71f1665b.PNG)
Nice website [fjaokdp](https://github.com/fjaokdp)!

**Comment by XYN0N** [comment]
![image](https://user-images.githubusercontent.com/46033510/235300554-774acf88-a469-4e6c-971c-6d53a93d7bb3.png)
